<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <RootNamespace>OSVersionExt</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>OSVersionExt</PackageId>
    <Version>4.1.0</Version>
    <Title>OSVersionExt</Title>
    <Authors>Stefan Prugg</Authors>
    <Copyright>Copyright © 2023 Stefan Prugg under MIT license</Copyright>
    <Description>Detect Windows version – Windows 11, Windows 2025 Server and earlier versions.</Description>
    <PackageTags>windows version</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/pruggitorg/detect-windows-version</RepositoryUrl>
    <PackageProjectUrl>https://github.com/pruggitorg/detect-windows-version</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReleaseNotes>Added support for Windows 2025 Server detection.</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

</Project>
